image: Visual Studio 2017
version: '1.0.{build}'
shallow_clone: false
skip_branch_with_pr: true
services:
- docker

branches:
  only:
    - master

environment:
  PS_GELLERY_RELEASE_API:
    secure: xBR5JNFYMUisp+oIx08EbfQ5xWsToa0XufJKuyaazeXy9wYcs6Fezw//NtW60uOF

install:
  - pwsh --version
  - pwsh -command Install-Module Pester -Scope CurrentUser

build: off

build_script:
  - pwsh -file ./build_psd1.ps1 -Version %APPVEYOR_BUILD_VERSION% -TagVersion "%APPVEYOR_REPO_TAG_NAME%"
  - 7z a "%APPVEYOR_BUILD_FOLDER%/publish/ScoopPlaybook_%APPVEYOR_BUILD_VERSION%.zip" "%APPVEYOR_BUILD_FOLDER%/publish/ScoopPlaybook/"

test_script:
  - pwsh -command Invoke-Pester -CodeCoverage src/ScoopPlaybook.psm1

deploy_script:
  - pwsh -file ./deploy_pagallery.ps1 -NuGetApiKey %PS_GELLERY_RELEASE_API% -BuildBranch master -ModuleName ScoopPlaybook -TagVersion "%APPVEYOR_REPO_TAG_NAME%"

artifacts:
  - path: ./publish/ScoopPlaybook_%APPVEYOR_BUILD_VERSION%.zip
    name: ScoopPlaybook_%APPVEYOR_BUILD_VERSION%
