name: build
on: [pull_request]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - run: . ./build_psd1.ps1 -Version ${{ github.run_id }} -TagVersion "0.1.0"
        shell: pwsh
      - uses: docker://devblackops/github-action-psscriptanalyzer:2.0.0
        with:
          rootPath: src/
          settingsPath: src/ScoopPlaybook.psd1
          sendComment: true
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          failOnErrors: true
          failOnWarnings: true
          failOnInfos: true
      - run: 7z a "./publish/ScoopPlaybook_${{ github.run_id }}.zip" "./publish/ScoopPlaybook/"
        shell: pwsh
      - uses: actions/upload-artifact@v2
        with:
          name: ScoopPlaybook_${{ github.run_id }}.zip
          path: ./publish/ScoopPlaybook_${{ github.run_id }}.zip
