name: build
on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.

  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
          Install-Module -Name PowerShell-Yaml -Scope CurrentUser -Force
          Install-Module -Name Pester -Scope CurrentUser -Force
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src -Settings ./PSScriptAnalyzerSettings.psd1 -Severity Warning
          Invoke-ScriptAnalyzer -Path ./src/ScoopPlaybook.psm1 -Settings CodeFormatting
      # Actions shell is Administartor. see https://github.com/ScoopInstaller/Install#for-admin
      # Need install scoop in same run of Invoke-Pester.
      - name: Run Unit Test
        shell: pwsh
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop
          echo "* Show Scoop version"
          scoop --version
          echo "* Show Scoop buckets"
          scoop bucket list
          echo "* Show Scoop apps"
          scoop list
          echo "* Install git"
          scoop install git
          echo "* Begin test"
          Invoke-Pester -CI
