name: build
on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Install Modules
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force
          Install-Module PowerShell-Yaml -Scope CurrentUser -Force
          Install-Module -Name Pester -Scope CurrentUser -Force
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          Invoke-ScriptAnalyzer -Path ./src -Settings ./PSScriptAnalyzerSettings.psd1 -Severity Warning
          Invoke-ScriptAnalyzer -Path ./src/ScoopPlaybook.psm1 -Settings CodeFormatting
      # Actions shell is Administartor. see https://github.com/ScoopInstaller/Install#for-admin
      # Need install scoop in same run of Invoke-Pester.
      - name: Run Unit Test
        shell: pwsh
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop
          scoop bucket list
          scoop list
          scoop install git
          Invoke-Pester -CI
