name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - run: Install-Module -Name PSScriptAnalyzer -Scope CurrentUser -Force && Invoke-ScriptAnalyzer -Path ./src -Settings ./PSScriptAnalyzerSettings.psd1
        shell: pwsh
