name: PowerShell Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: install modules
      run: |
        pwsh --version
        pwsh -command Install-Module Pester -Scope CurrentUser -Force
        pwsh -command Install-Module PowerShell-Yaml -Scope CurrentUser
    - pwsh: ./build_psd1.ps1 -Version %APPVEYOR_BUILD_VERSION% -TagVersion "%APPVEYOR_REPO_TAG_NAME%"
    - pwsh: Invoke-Pester -CodeCoverage src/ScoopPlaybook.psm1
