name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - run: echo "::set-env name=$(GIT_TAG::$GITHUB_REF.Replace('refs/tags/', ''))"
      - uses: actions/checkout@v2
      - run: . ./build_psd1.ps1 -Version ${{ github.run_id }} -TagVersion $env:GIT_TAG
        shell: pwsh
      - uses: actions/upload-artifact@v2
        with:
          name: ScoopPlaybook_${{ env.GIT_TAG }}.zip
          path: ./publish/ScoopPlaybook_${{ env.GIT_TAG }}.zip
      # - run: ./deploy_pagallery.ps1 -Key $env:NUGET_API_KEY
      #   shell: pwsh
      #   env:
      #     KEY: ${{ secrets.SYNCED_PSGALLERY_NUGET_KEY }}
