name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
        shell: bash
        env:
          REF: ${{ github.ref }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: . ./publish.ps1 -Version $env:GIT_TAG
        shell: pwsh
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: ScoopPlaybook_${{ env.GIT_TAG }}.zip
          path: ./publish/ScoopPlaybook_${{ env.GIT_TAG }}.zip
      - run: ./push.ps1 -Key $env:KEY -DryRun $false
        shell: pwsh
        env:
          KEY: ${{ secrets.SYNCED_PSGALLERY_NUGET_KEY }}
      - uses: actions/create-release@0cb9c9b65d5d1901c1f53e5e66eaf4afd303e70e # v1.1.4
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
