name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*" # only tag

jobs:
  release:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
      - run: echo "GIT_TAG=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
        shell: bash
        env:
          REF: ${{ github.ref }}
      - uses: actions/checkout@v3
      - run: . ./publish.ps1 -Version $env:GIT_TAG
        shell: pwsh
      - uses: actions/upload-artifact@v2
        with:
          name: ScoopPlaybook_${{ env.GIT_TAG }}.zip
          path: ./publish/ScoopPlaybook_${{ env.GIT_TAG }}.zip
      - run: ./push.ps1 -Key $env:KEY -DryRun $false
        shell: pwsh
        env:
          KEY: ${{ secrets.SYNCED_PSGALLERY_NUGET_KEY }}
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
